### ISSUE TITLE
Template não encontrado

### ISSUE THREAD

**Issue by Isaias-Vasconcelos** [thiagocorreanet/CleanArchSolution#4]
Após a instalação da extensão, a mesma não aparece na listagem de templates de projeto no visual studio 2022. 

Usando a configuração padrão de fabrica do vs.

![image](https://github.com/user-attachments/assets/2b023063-2406-415f-91a5-82854e4c258c)

![image](https://github.com/user-attachments/assets/a5df7a1a-2bab-4aa4-ae0b-01b8899e9f91)

**Comment by Isaias-Vasconcelos** [comment]
Bug resolvido! 

![image](https://github.com/user-attachments/assets/5307e413-b235-414f-b7df-0ad61c7b6fce)

**Comment by thiagocorreanet** [comment]
Problema foi resolvido, dentro do arquivo de configuração do template precisou adicionar as seguintes tags

![image](https://github.com/user-attachments/assets/7fef5483-47f6-4f17-b904-d2fa813e5ba8)
